name: Deploy GU-VPC Infraestructura

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente a desplegar (dev, qa, prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Init
        run: terraform init
        working-directory: ./

      - name: Plan
        run: terraform plan -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars"
        working-directory: ./

      - name: Apply
        run: terraform apply -auto-approve -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars"
        working-directory: ./
